name: emailjs
description: EmailJS helps sending emails directly from the Flutter app. No server is required.
version: 4.0.0
homepage: https://www.emailjs.com
repository: https://github.com/emailjs-com/emailjs-flutter

environment:
  sdk: '>=2.18.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.3
